-- Migration: 2026-04-17 - Storage bucket RLS policies for Supabase storage
-- Purpose: Add Row Level Security policies for `storage.objects` to safely
-- allow authenticated users to upload/delete/update objects in their own
-- folders for the `materials` and `avatars` buckets.
--
-- IMPORTANT:
-- 1) This file only creates RLS policies on the Postgres table backing
--    Supabase Storage (storage.objects). You still need to *create the
--    buckets* (`avatars`, `materials`) in the Supabase Storage dashboard
--    (or via API) and configure whether they are public or private.
-- 2) If you set a bucket to PUBLIC in Supabase, public URLs generated by
--    `getPublicUrl()` will work regardless of these policies. If you keep
--    the bucket PRIVATE, these policies control database-level access.
-- 3) Review and adjust the `LIKE` patterns if your upload naming differs.
-- 4) Always backup production database before applying new policies.

-- Enable RLS on storage.objects (idempotent)
ALTER TABLE IF EXISTS storage.objects ENABLE ROW LEVEL SECURITY;

-- Clean up existing policies we will replace (idempotent)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'storage_select_public') THEN
    EXECUTE 'DROP POLICY IF EXISTS "storage_select_public" ON storage.objects';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'storage_insert_user_materials') THEN
    EXECUTE 'DROP POLICY IF EXISTS "storage_insert_user_materials" ON storage.objects';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'storage_insert_user_avatars') THEN
    EXECUTE 'DROP POLICY IF EXISTS "storage_insert_user_avatars" ON storage.objects';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'storage_update_owner') THEN
    EXECUTE 'DROP POLICY IF EXISTS "storage_update_owner" ON storage.objects';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'storage_delete_owner') THEN
    EXECUTE 'DROP POLICY IF EXISTS "storage_delete_owner" ON storage.objects';
  END IF;
END$$;

-- Allow SELECT (read) for commonly public buckets (adjust as needed).
-- If you keep buckets private, restrict this policy or remove it.
CREATE POLICY "storage_select_public"
  ON storage.objects
  FOR SELECT
  USING (
    bucket_id IN ('avatars', 'materials')
  );

-- Allow INSERT into `materials` only when the object name starts with the
-- authenticated user's id followed by a slash (we store files under: userId/filename).
CREATE POLICY "storage_insert_user_materials"
  ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'materials'
    AND auth.uid() IS NOT NULL
    AND name LIKE auth.uid() || '/%'
  );

-- Allow INSERT into `avatars` only when object name begins with user id
-- followed by '-' (pattern used in `Profile.tsx`) OR user id + '/'.
CREATE POLICY "storage_insert_user_avatars"
  ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'avatars'
    AND auth.uid() IS NOT NULL
    AND (
      name LIKE auth.uid() || '-%'
      OR name LIKE auth.uid() || '/%'
      OR name LIKE auth.uid() || '%'
    )
  );

-- Allow UPDATE only for owners (object name starting with their uid)
CREATE POLICY "storage_update_owner"
  ON storage.objects
  FOR UPDATE
  USING (
    auth.uid() IS NOT NULL
    AND (
      name LIKE auth.uid() || '/%'
      OR name LIKE auth.uid() || '-%'
      OR name LIKE auth.uid() || '%'
    )
  )
  WITH CHECK (
    true
  );

-- Allow DELETE only for owners (object name starting with their uid)
CREATE POLICY "storage_delete_owner"
  ON storage.objects
  FOR DELETE
  USING (
    auth.uid() IS NOT NULL
    AND (
      name LIKE auth.uid() || '/%'
      OR name LIKE auth.uid() || '-%'
      OR name LIKE auth.uid() || '%'
    )
  );

-- Notes: If you use different naming conventions for uploaded files, adjust
-- the `LIKE` patterns above. For example, to allow uploads to a tenant
-- folder, match the tenant id instead of `auth.uid()`.

-- End of migration
